## google raw data preprocessing
1. 컬럼 추가
2. 추출시간 데이터타입 변경
3. 가격 (',원) 제거
4. 결측치 제거
5. 도착시간 형식 변경

In [7]:
import pandas as pd
import numpy as np 
import datetime
import os
import re 

file_name = 'google_bangkok_26'
file_name1 = 'google_bangkok_27'
file_name2 = 'google_danang_26'
file_name3 = 'google_danang_27'
file_name4 = 'google_osaka_26'
file_name5 = 'google_osaka_27'

col_names = ['항공사', '출발시간', '출발공항', '도착시간', '도착공항',
            '비행방식', '소요시간', '추출시간', '편도/왕복', '가격', '편명']

df = pd.read_csv("/", encoding="utf-8")
df1 = pd.read_csv("/", encoding="utf-8")
df2 = pd.read_csv(f"/", encoding="utf-8")
df3 = pd.read_csv("/", encoding="utf-8")
df4 = pd.read_csv("/", encoding="utf-8")
df5 = pd.read_csv("/", encoding="utf-8")

df.columns = col_names
df1.columns = col_names
df2.columns = col_names
df3.columns = col_names
df4.columns = col_names
df5.columns = col_names


df['추출시간'] = pd.to_datetime(df['추출시간'])
df1['추출시간'] = pd.to_datetime(df1['추출시간'])
df2['추출시간'] = pd.to_datetime(df2['추출시간'])
df3['추출시간'] = pd.to_datetime(df3['추출시간'])
df4['추출시간'] = pd.to_datetime(df4['추출시간'])
df5['추출시간'] = pd.to_datetime(df5['추출시간'])

df = df[df['가격'].notna()].reset_index(drop=True)
df1 = df1[df1['가격'].notna()].reset_index(drop=True)
df2 = df2[df2['가격'].notna()].reset_index(drop=True)
df3 = df3[df3['가격'].notna()].reset_index(drop=True)
df4 = df4[df4['가격'].notna()].reset_index(drop=True)
df5 = df5[df5['가격'].notna()].reset_index(drop=True)

# 가격 , 원 제거 및 int 형으로
df['가격'] = df['가격'].str.replace(',', '').str.replace('원', '').astype(int)
df1['가격'] = df1['가격'].str.replace(',', '').str.replace('원', '').astype(int)
df2['가격'] = df2['가격'].str.replace(',', '').str.replace('원', '').astype(int)
df3['가격'] = df3['가격'].str.replace(',', '').str.replace('원', '').astype(int)
df4['가격'] = df4['가격'].str.replace(',', '').str.replace('원', '').astype(int)
df5['가격'] = df5['가격'].str.replace(',', '').str.replace('원', '').astype(int)

# 항공사 명 변경
# df = df.replace({'항공사':'Apg Distribution System'}, 'APG항공')

In [12]:
# 결측치 제거
df = df.dropna()
df1 = df1.dropna()
df2 = df2.dropna()
df3 = df3.dropna()
df4 = df4.dropna()
df5 = df5.dropna()

In [32]:
df

,항공사,출발시간,출발공항,도착시간,도착공항,비행방식,소요시간,추출시간,편도/왕복,가격,편명
0,베트남항공,10:45,ICN,13:55,DAD,직항,05시간 10분,2024-01-20 00:00:00,편도,548500,VN 431
1,티웨이항공,7:45,ICN,10:55,DAD,직항,05시간 10분,2024-01-20 00:00:00,편도,561000,TW 125
2,티웨이항공,19:25,ICN,22:35,DAD,직항,05시간 10분,2024-01-20 00:00:00,편도,561000,TW 191
3,티웨이항공,20:20,ICN,23:35,DAD,직항,05시간 15분,2024-01-20 00:00:00,편도,561000,TW 127
4,제주항공,10:40,ICN,13:45,DAD,직항,05시간 00분,2024-01-20 00:00:00,편도,567000,7C 2901
...,...,...,...,...,...,...,...,...,...,...,...
1362,비엣젯항공,6:15,ICN,9:20,DAD,직항,05시간 00분,2024-01-22 10:00:00,편도,583607,VJ 881
1363,대한항공,18:30,ICN,21:45,DAD,직항,05시간 15분,2024-01-22 10:00:00,편도,612400,KE 461
1364,진에어,21:10,ICN,24:25,DAD,직항,05시간 15분,2024-01-22 10:00:00,편도,623600,LJ 69
1365,아시아나,18:45,ICN,21:50,DAD,직항,05시간 00분,2024-01-22 10:00:00,편도,770100,OZ 755
1366,대한항공,11:10,ICN,14:15,DAD,직항,05시간 00분,2024-01-22 10:00:00,편도,780000,KE 457

In [14]:
# 파일 저장
df.to_csv(os.path.join("../../data/eda_project/pre_prosessing_data/google_22일_10:00까지/", f"refined_{file_name}.csv"))
df1.to_csv(os.path.join("../../data/eda_project/pre_prosessing_data/google_22일_10:00까지/", f"refined_{file_name1}.csv"))
df2.to_csv(os.path.join("../../data/eda_project/pre_prosessing_data/google_22일_10:00까지/", f"refined_{file_name2}.csv"))
df3.to_csv(os.path.join("../../data/eda_project/pre_prosessing_data/google_22일_10:00까지/", f"refined_{file_name3}.csv"))
df4.to_csv(os.path.join("../../data/eda_project/pre_prosessing_data/google_22일_10:00까지/", f"refined_{file_name4}.csv"))
df5.to_csv(os.path.join("../../data/eda_project/pre_prosessing_data/google_22일_10:00까지/", f"refined_{file_name5}.csv"))

In [15]:
#csv 파일 있는 경로 입력해주기
path = "/"

In [16]:
flight_raw_data_bangkok_26 = pd.read_csv(path+"refined_google_bangkok_26.csv")
flight_raw_data_bangkok_27 = pd.read_csv(path+"refined_google_bangkok_27.csv")
flight_raw_data_danang_26 = pd.read_csv(path+"refined_google_danang_26.csv")
flight_raw_data_danang_27 = pd.read_csv(path+"refined_google_danang_27.csv")
flight_raw_data_osaka_26 = pd.read_csv(path+"refined_google_osaka_26.csv")
flight_raw_data_osaka_27 = pd.read_csv(path+"refined_google_osaka_27.csv")

In [17]:
df_list = [flight_raw_data_bangkok_26, flight_raw_data_bangkok_27,flight_raw_data_danang_26,
            flight_raw_data_danang_27,flight_raw_data_osaka_26, flight_raw_data_osaka_27]

In [18]:
for value in df_list:
    for i in range(len(value["출발시간"])):

        tmp = value["출발시간"].iloc[i]
        hour = re.search("\d+(\d+)?:", tmp).group()
        minute = re.search(":\d+\d+", tmp).group()

        hour = hour.replace(":", "")

        if int(hour) >= 24:
            hour = str(int(hour) - 24)

        hour = "{:02d}".format(int(hour))

        # 변경된 값을 다시 데이터프레임에 할당
        value.at[i, "출발시간"] = hour + minute

In [19]:
for value in df_list:
    for i in range(len(value["도착시간"])):
        tmp = value["도착시간"].iloc[i]

        hour = re.search("\d+(\d+)?:", tmp).group()
        minute = re.search(":\d+\d+", tmp).group()

        hour = hour.replace(":", "")

        if int(hour) >= 24:
            hour = str(int(hour) - 24)

        hour = "{:02d}".format(int(hour))

        # 변경된 값을 다시 데이터프레임에 할당
        value.at[i, "도착시간"] = hour + minute

In [20]:
naver_order = ['항공사', '출발시간', '출발공항', '도착시간', '도착공항',
            '비행방식', '소요시간', '편도/왕복', '가격', '추출시간', '편명']

In [21]:
# 네이버 항공편 순서대로 바꾸기
flight_raw_data_bangkok_26 = flight_raw_data_bangkok_26[naver_order]
flight_raw_data_bangkok_27 = flight_raw_data_bangkok_27[naver_order]
flight_raw_data_danang_26 = flight_raw_data_danang_26[naver_order]
flight_raw_data_danang_27 = flight_raw_data_danang_27[naver_order]
flight_raw_data_osaka_26 = flight_raw_data_osaka_26[naver_order]
flight_raw_data_osaka_27 = flight_raw_data_osaka_27[naver_order]

In [22]:
flight_raw_data_bangkok_26.to_csv(path+"conv/google_bangkok_26.csv", encoding="utf-8")
flight_raw_data_bangkok_27.to_csv(path+"conv/google_bangkok_27.csv", encoding="utf-8")
flight_raw_data_danang_26.to_csv(path+"conv/google_danang_26.csv", encoding="utf-8")
flight_raw_data_danang_27.to_csv(path+"conv/google_danang_27.csv", encoding="utf-8")
flight_raw_data_osaka_26.to_csv(path+"conv/google_osaka_26.csv", encoding="utf-8")
flight_raw_data_osaka_27.to_csv(path+"conv/google_osaka_27.csv", encoding="utf-8")